# Generated by Django 3.0.6 on 2021-02-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='TermRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Term', verbose_name='용어')),
            ],
        ),
        migrations.CreateModel(
            name='TermRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='wiki.Term')),
                ('term_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_related', to='wiki.Term')),
            ],
        ),
        migrations.CreateModel(
            name='TermPointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Term')),
                ('term_revision', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.TermRevision')),
            ],
        ),
    ]
