# Generated by Django 3.1 on 2020-09-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termpointer',
            old_name='term_link',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='termpointer',
            old_name='term_revision_link',
            new_name='term_revision',
        ),
    ]
